### ISSUE TITLE
Keynote Speakers suggestion

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024-tasks#24]
## Tasks
 - [x] Prepare the Github discussion with the appropriate description 
 - [x] Create a bitly URL for the Github discussion for social media posts.
 - [x] Prepare the content for the mailing list @Sc0rpi0n101
 - [x] Prepare the content for the social media post, along with the picture @Sc0rpi0n101

### Post 4PM
 - [x] Post on the inpycon mailing list @WatchfulHitman
 - [x] Post on the social media channels, Instagram, Facebook, and Twitter @WatchfulHitman
    * Limit the conversation on Twitter so that people cannot reply on Twitter.
 - [ ] Send to other Python Mailing lists (BangPypers, PythonPune, HydPy, PyDelhi, ChennaiPy, MumbaiPy) @WatchfulHitman

Ref: [Mailing List Guidelines](https://github.com/pythonindia/inpycon2024-tasks/wiki/PyCon-India-2024)

**Comment by anistark** [comment]
Mailing List Content by Nikhil:

```
Hi everyone!

As you might already know, the preparations for PyCon India 2024 are underway[1]. We want to kick off the process of selecting the Keynote Speakers for the conference.

If you're new to PyCon India, our keynotes are a highlight; they're not just talks but impactful presentations delivered by distinguished community members. They provide valuable insights and perspectives from their experiences, genuinely elevating the conference atmosphere.

Please share your keynote speaker suggestions on the GitHub Discussion [2]. Please remember to send in one keynote speaker suggestion per comment containing a brief description of the speaker or include a link to the speaker's bio. If you like a speaker suggestion, please vote by writing a line about your vote, e.g., "I would also love to hear X as a keynote speaker [because of these Y reasons]".

We encourage suggestions from both Indian and international backgrounds as we aim to create a diverse lineup.

We will start reaching out to keynote speakers in the order of preference
within the next few weeks. Please suggest your keynote speakers by March 10th 23:59 IST.

[1]. https://mail.python.org/pipermail/inpycon/2024-January/013416.html
[2]. https://github.com/pythonindia/inpycon2024-tasks/discussions/25

Regards,
*Team PyCon India 2024*
```
