### ISSUE TITLE
PyCon India 2024 CFP announcement

### ISSUE THREAD

**Issue by wavicles** [pythonindia/inpycon2024-tasks#30]
Scheduled for **10th March 2024**

## Tasks
- [x] [Junction setup for 2024](https://in.pycon.org/cfp/2024/proposals/)
- [x] Prepare a blog post  for CFP @Sc0rpi0n101
- [x] Prepare the content for the social media post, along with the picture   @Sc0rpi0n101
- [x] Social media announcement @WatchfulHitman
- [ ] Mailing list announcement  @WatchfulHitman

### Pre 4 PM
- [x] Set up Junction for CFP 2024 @wavicles 
- [x] Verify the contents of Junction @anistark 
- [x] Merge the blog post
- [x] Draft the social media announcement  @WatchfulHitman
- [x] Add a CFP button on the main website  

### Post 5 PM
- [x] Deploy the blog and the website @palnabarun 
- [x] Send the social media announcements out  @WatchfulHitman
- [ ] Announce on mailing list  @WatchfulHitman
- [ ] Send to other Python Mailing lists (BangPypers, PythonPune, HydPy, PyDelhi, ChennaiPy, MumbaiPy) @WatchfulHitman

**Comment by wavicles** [comment]
- [x] Need to update this wiki page - https://github.com/pythonindia/junction/wiki/Speaker-best-practices

**Comment by Sc0rpi0n101** [comment]
Please find the content for Twitter @WatchfulHitman 
```
Drumroll, please! This year, the premier Python conference of India, PyCon India 2024, is coming to Bangalore! Join us for an unforgettable conference in the heart of India's tech hub! #PyConIndia #Python #Bangalore

Have you got a brilliant Python idea? Want to share it with the world? The PyCon India 2024 CFP is open. Submit your proposals by 31 May 2024 here: https://in.pycon.org/cfp/2024/proposals/. #PyConIndia #Python #CFP
```

**Comment by Sc0rpi0n101** [comment]
here's the content for the mailing list:
```
Hi Everyone

We are thrilled to announce that PyCon India 2024 will take place in Bangalore[1]. We are now accepting your proposals through our Call for Proposals [2]. This is your chance to contribute to the event and share your insights with the Python community.

Here are some important details about the CFP:

- We've opened the CFP today, 10 Mar 2024.
- The last CFP submission date will be 31 May 2024.
- We will also have rehearsal talks to prepare speakers and content,
details of which will be discussed later and announced
accordingly.

If you've any doubts or thoughts regarding the above, please feel free to
respond here or reach out to any of us on [Zulip][3].

We have also announced the Call for Proposals on our social
media[4][5][6][7]. Please help us spread the word to get even more
amazing talks this year.

Once again, we look forward to all your support in making this year's PyCon India a grand success.

[1]: https://in.pycon.org/2024/
[2]: https://in.pycon.org/cfp/2024/proposals/
[3]: https://pyconindia.zulipchat.com/
[4]:
[5]:
[6]:
[7]:
```

**Comment by Sc0rpi0n101** [comment]
I'm not entirely sure how to announce the logo in the mail, any suggestions for that?
Also, will be pushing the blog in a bit.

**Comment by iamaravindsekar** [comment]
Hey @Sc0rpi0n101 what about telling something like the logo this time revolves around a theme with cherry blossoms which is so famous with Bengaluru and then we have put people's favouite monuments that represent Bengaluru.

**Comment by Sc0rpi0n101** [comment]
Thanks for the suggestion @iamaravindsekar. I've updated the email comment. Please check and see if this works.

**Comment by Sc0rpi0n101** [comment]
I've added a PR for the blog: https://github.com/pythonindia/inpycon-blog/pull/440
Please review @anistark @wavicles

**Comment by WatchfulHitman** [comment]
Hi Everyone,

We are thrilled to announce that PyCon India 2024 will take place in Bengaluru[1]. We are now accepting your proposals through our Call for Proposals [2]. This is your chance to contribute to the event and share your insights with the Python community.

Here are some important details about the CFP:

- We've opened the CFP today, 10 Mar 2024.
- The last CFP submission date will be 31 May 2024.
- We will also have rehearsal talks to prepare speakers and content,
details of which will be discussed later and announced
accordingly.

We would also like to thank you for voting for your favorite logos. We have finalized the logo. The logo this time revolves around a theme with cherry blossoms, which are famous in Bengaluru and have people's favorite monuments that represent Bengaluru.

If you've any doubts or thoughts regarding the above, please feel free to
respond here or reach out to any of us on [Zulip][3].

We have also announced the Call for Proposals on our social
media[4][5][6][7].To Learn more about the CFP[8]. Please help us spread the word to get even more
amazing talks this year.

Once again, we look forward to all your support in making this year's PyCon India a grand success.

[1]: https://in.pycon.org/2024/
[2]: https://in.pycon.org/cfp/2024/proposals/
[3]: https://pyconindia.zulipchat.com/
[4]:https://twitter.com/pyconindia/status/1766821889144721460?t=dDZ2eV_43zoSghbzM-z7uA&s=19
[5]:https://www.instagram.com/p/C4VhIkWhR53/?igsh=ZjRld2V6YzFkYTI0 
[6]:https://www.facebook.com/share/p/JD94a55GcFoogiQb/?mibextid=Nif5oz
[7]:https://www.linkedin.com/posts/pyconindia_pyconindia-python-cfp-activity-7172595963272814592-Ljyh?utm_source=share&utm_medium=member_android
[8]: https://in.pycon.org/blog/2024/cfp-logo-announcement.html

Regards,
Akashnil Roy
On behalf of PyCon India 2024 Team
https://in.pycon.org/2024/


Here is the final content for mailing lists. Feedback are most welcome.

**Comment by anistark** [comment]
It's not "CFP today, 10 Mar" anymore.

Also, don't abbreviate anything on mail. Write full text, "March".
