### ISSUE TITLE
Workshop and Combo Tickets

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024-tasks#34]
We'll be opening Workshop and Combo tickets on Friday 26th April 6pm.

# Tasks

## Content  WG @Sc0rpi0n101 

- [ ] Mailing List announcement 
- [ ] Twitter Thread post 
- [ ] Linkedin, Facebook, Mastodon, Instagram

## Design WG @iamaravindsekar

- [ ] Social Media Post 1:1

## Comms WG @WatchfulHitman 

- [ ] Inpycon Mailing List
- [ ] X-Post on other mailing lists
- [ ] Twitter
- [ ] Linkedin
- [ ] Mastodon
- [ ] Instagram
- [ ] Facebook

**Comment by Sc0rpi0n101** [comment]
Email Content: 
```
Hello Everyone,

PyCon India 2024 Workshop and Combo tickets are now available. The combo tickets grant you access to all 3 conference days, including the fantastic talks, keynotes, interactive workshops, and dev sprints. Don't miss out on this opportunity. Buy your tickets now[1].

Quick Summary:
--------------

PyCon India 2024 is happening in Bengaluru from 20th Sep 2021 to 23rd Sep 2024.
* WorkShop Days: 20th Sep, 2024
* Conference Days: 21st-22nd Sep, 2024
* Dev sprints: 23rd Sep, 2024

If you have any questions or suggestions, Do reach out to us on Zulip[2]

Please help us spread this message by sharing it on your social networks as widely as possible. Thank you!

Links:

[0] https://in.pycon.org/2024/

[1] https://konfhub.com/pyconindia2024

[2] https://pyconindia.zulipchat.com/

Tweet:
LinkedIn:

Thanks,
```

**Comment by Sc0rpi0n101** [comment]
Tweet content 
```
Attention Pythonistas :snake:

:fire:  The Combo and Workshop tickets for PyCon India 2024 are now live!
While the Combo ticket gives you access to all 3 days of PyCon India 2024, with the Workshop ticket, you can attend any workshop you want on the Workshop day :tada:
Don't miss the opportunity to attend India's premier Python conference. Grab your tickets now! See you super soon at the conference [#Python #PyConIndia2024](https://twitter.com/hashtag/PyConIndia2024?src=hashtag_click)

Link : https://in.pycon.org/2024/
```
If it's still above character limit, please remove stuff as per your discretion @WatchfulHitman

**Comment by anistark** [comment]
@ananyo2012 @WatchfulHitman if this is all done, can we mark each and close it?
