### ISSUE TITLE
Call for Sponsors Announcement and Website update with sponsorship prospectus

### ISSUE THREAD

**Issue by abhishekmishragithub** [pythonindia/inpycon2024-tasks#35]
We'll be announcing about sponsorship (with prospectus) on Monday 1st May 6pm.

# Tasks

## Content WG @Sc0rpi0n101
- [ ] Mailing List announcement
- [ ] Twitter Thread post
- [ ] Linkedin, Facebook, Mastodon, Instagram

## Design WG @iamaravindsekar

- [ ] Social Media Post 1:1

## Comms WG @WatchfulHitman

- [ ] Inpycon Mailing List
- [ ] X-Post on other mailing lists
- [ ] Twitter
- [ ] Linkedin
- [ ] Mastodon
- [ ] Instagram
- [ ] Facebook

## Tech/Website @palnabarun/@bhansa 

- [ ] /sponsors slug and page 
- [ ] "Download Prospectus" button on sponsorship page
Ref page: https://in.pycon.org/2023/#sponsors

## Sponsorship WG @abhishekmishragithub
- [ ] send email to initial interested sponsors

**Comment by abhishekmishragithub** [comment]
Here is the PDF doc. 
[Uploading pycon_india_2024_sponsorship_prospectus.pdf…]()

**Comment by abhishekmishragithub** [comment]
PS: Updated the date to 1st May 6pm.

**Comment by abhishekmishragithub** [comment]
here is the updated prospectus: https://drive.google.com/file/d/18MoAFF148ijpRV_xwU41bT2juEbDkxUx/view @bhansa @Sc0rpi0n101 
and here is the short URL for social media post: https://bit.ly/sponsorship-pycon-india @WatchfulHitman

**Comment by Sc0rpi0n101** [comment]
Email content:
```
Hello,

I hope you all are doing well. The call for Sponsors is now open for PyCon India 2024[0]

Organizations with an interest in contributing and adding value to the
event and Python community can come forward to make the most out of
this opportunity.

The sponsorship prospectus is available at: [1]

What's in it for the sponsors?

This act of goodwill while giving back to the community helps sponsors
increase their brand exposure and elevate their business identity
within the Python community.

Sponsorship Slabs
----------------------


  * Platinum - Rs. 8,00,000 (INR) or $11,499 (USD)
  * Gold - Rs. 6,00,000 (INR) or $8,599 (USD)
  * Silver - Rs. 3,00,000 (INR) or $4,299 (USD)
  * Associate - Rs. 1,00,000 (INR) or $1,499 (USD)
  * Discount
    - 50% discount for startups with 15 employees or less
    - And less than 3 years
    - Applicable for Associate

Links:
[0] [https://in.pycon.org/blog/2024/call-for-sponsors](https://in.pycon.org/blog/2021/call-for-in-kind-sponsors.html)
[1] bit.ly/inpycon-sponsor


Conference tickets are still open; you can grab them here: [https://in.pycon.org/2024/](https://in.pycon.org/2021/).

If you have any questions or suggestions, Do reach out to us on Zulip:
https://pyconindia.zulipchat.com/

Thanks,
```

**Comment by Sc0rpi0n101** [comment]
How is this for the tweet content: 
```

Is your comapny looking for a way to connect with the Python community and establish your brand among the professionals, students, and enthusiasts of the community? Look no further than PyCon India 2024! Become a sponsor today and enjoy a wide range of benefits and opportunities. So why wait? Visit [link] right now to learn more.
```

**Comment by Sc0rpi0n101** [comment]
@abhishekmishragithub @WatchfulHitman lemme know if you have any feedback on these or need me to change something.

**Comment by Sc0rpi0n101** [comment]
and the blog PR: https://github.com/pythonindia/inpycon-blog/pull/443

**Comment by abhishekmishragithub** [comment]
> Links:
> [0] [https://in.pycon.org/blog/2024/call-for-sponsors](https://in.pycon.org/blog/2021/call-for-in-kind-sponsors.html)
> 

this URL is wrong right? why you putting inkind sponsors blog URL?

**Comment by abhishekmishragithub** [comment]
> Email content:
> 
> ```
> Hello,
> 
> I hope you all are doing well. The call for Sponsors is now open for PyCon India 2024[0]
> 
> Organizations with an interest in contributing and adding value to the
> event and Python community can come forward to make the most out of
> this opportunity.
> 
> The sponsorship prospectus is available at: [1]
> 
> What's in it for the sponsors?
> 
> This act of goodwill while giving back to the community helps sponsors
> increase their brand exposure and elevate their business identity
> within the Python community.
> 
> Sponsorship Slabs
> ----------------------
> 
> 
>   * Platinum - Rs. 8,00,000 (INR) or $11,499 (USD)
>   * Gold - Rs. 6,00,000 (INR) or $8,599 (USD)
>   * Silver - Rs. 3,00,000 (INR) or $4,299 (USD)
>   * Associate - Rs. 1,00,000 (INR) or $1,499 (USD)
>   * Discount
>     - 50% discount for startups with 15 employees or less
>     - And less than 3 years
>     - Applicable for Associate
> 
> Links:
> [0] [https://in.pycon.org/blog/2024/call-for-sponsors](https://in.pycon.org/blog/2021/call-for-in-kind-sponsors.html)
> [1] bit.ly/inpycon-sponsor
> 
> 
> Conference tickets are still open; you can grab them here: [https://in.pycon.org/2024/](https://in.pycon.org/2021/).
> 
> If you have any questions or suggestions, Do reach out to us on Zulip:
> https://pyconindia.zulipchat.com/
> 
> Thanks,
> ```

I think we should also add "Other Sponros" type here and reference the prospectus to read more about it. @anistark do you think the blog should have those information as well? or not required ?

**Comment by Sc0rpi0n101** [comment]
> > Links:
> > [0] [https://in.pycon.org/blog/2024/call-for-sponsors](https://in.pycon.org/blog/2021/call-for-in-kind-sponsors.html)
> 
> this URL is wrong right? why you putting inkind sponsors blog URL?

Updated it, sorry.

**Comment by anistark** [comment]
Yeah let's come up with a better name than "Other".

Maybe "Special Sponsors" ?
