### ISSUE TITLE
Announce First Keynote

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024-tasks#38]
Announcing Kovid as the 1st Keynote.
Announcement Date: May 15, 2024

## Tasks
- [ ] Social Media Poster @iamaravindsekar
- [ ] Social Media announcement @WatchfulHitman 
- [ ] Blog post announcement @Sc0rpi0n101  
- [ ] Mailing list announcement  @sayanchowdhury 
- [ ] Website update to display the first keynote speaker. @bhansa 

### Pre 4PM
- [x] Push a low resolution image to server to refer in website and blog @bhansa 
- [x] Merge the blog post @Sc0rpi0n101 
- [ ] Draft the social media announcement @WatchfulHitman  
- [x] Merge the website changes @bhansa  

### Post 5PM
- [x] Deploy the blog and the website @bhansa  
- [x] Send the social media announcements out @WatchfulHitman  
- [x] Announce on mailing list @sayanchowdhury 

### Communication Channel

- [x] Mailing List
  - [x] InPyCon
  - [x] X-Posts
    - [x] All Local Python User Groups
- [x] Social Media
  - [x]  Twitter
  - [x]  Linkedin
  - [x]  Mastodon
  - [x]  Instagram
  - [x]  Facebook

**Comment by sayanchowdhury** [comment]
I am the creator and ongoing maintainer of dozens of Python projects, with
millions of users. Most prominently calibre, the e-book management program
and kitty, the GPU accelerated terminal. Many of my Python projects are
focused speed, for example html5-parser which is 30x as fast as the
Python alternatives. Or kitty which has best in class performance
despite being written partly in Python.

https://kovidgoyal.net/images/kovid.jpg

**Comment by iamaravindsekar** [comment]
> I am the creator and ongoing maintainer of dozens of Python projects, with
> millions of users. Most prominently calibre, the e-book management program
> and kitty, the GPU accelerated terminal. Many of my Python projects are
> focused speed, for example html5-parser which is 30x as fast as the
> Python alternatives. Or kitty which has best in class performance
> despite being written partly in Python.
> 
> https://kovidgoyal.net/images/kovid.jpg

@sayanchowdhury would like to know what should be the Designation and Name of Organisation.. Shall I put "Principle Developer , Calibre and Kitty"

**Comment by iamaravindsekar** [comment]
Poster has been uploaded in Google drive and putting the share url for our first keynote speaker poster. Thank you 

https://drive.google.com/file/d/1_-Vpqr5PJMDrcKGmRKNG8bY4D6W9Dy6T/view?usp=share_link
