### ISSUE TITLE
CFP Promotion Blog Post 1 

### ISSUE THREAD

**Issue by wavicles** [pythonindia/inpycon2024-tasks#40]
Blog Post 1 Scheduled for **18 th May 2024**

**Speak, Share, Inspire: Join PyCon India 2024 as a Speaker**
Aimed at encouraging newbies and seasoned speakers to submit a proposal and join the community.
## Tasks
- [ ] Prepare a blog post draft   for CFP promotion and share it with the content team @wavicles @Sc0rpi0n101 
- [ ] Prepare draft content for the social media post and share it with com wg @wavicles
- [ ] Social media announcement @WatchfulHitman
- [ ] Mailing list announcement  @WatchfulHitman

### Pre 4 PM
- [ ] Merge the blog post @Sc0rpi0n101 
- [ ] Draft the social media and mailing list announcement  @WatchfulHitman
- 

### Post 5 PM
- [ ] Deploy the blog and the website @palnabarun 
- [ ] Send the social media announcements out  @WatchfulHitman
- [ ] Announce on mailing list  @WatchfulHitman
- [ ] Send to other Python Mailing lists (BangPypers, PythonPune, HydPy, PyDelhi, ChennaiPy, MumbaiPy) @WatchfulHitman

**Comment by wavicles** [comment]
Draft doc by @wavicles [Speak, Share, Inspire: Join PyCon India 2024 as a Speaker](https://docs.google.com/document/d/1pJwXcNfksr_bbF_33W-NzJ96zuhT7acqyQrwg-M88mM/edit?usp=sharing)

**Comment by anistark** [comment]
Guess this is done. @wavicles feel free to reopen if anything pending.
