### ISSUE TITLE
Update Navigator

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024-tasks#41]
[Navigator](https://navigator.in.pycon.org/) needs update in content.

## Tasks
- [ ] Issues to be assigned in [Navigator WG wise](https://github.com/pythonindia/navigator/issues)

## WGs Issues:

- [ ] [CFP](https://github.com/pythonindia/navigator/issues/22) 
- [ ] [Comms](https://github.com/pythonindia/navigator/issues/23)
- [ ] [CoC](https://github.com/pythonindia/navigator/issues/24)
- [ ] [Tech](https://github.com/pythonindia/navigator/issues/25)
- [ ] [Finance & Tickets](https://github.com/pythonindia/navigator/issues/26)
- [ ] [Sponsorship](https://github.com/pythonindia/navigator/issues/27)
- [ ] [Diversity](https://github.com/pythonindia/navigator/issues/28)
- [ ] [Creative](https://github.com/pythonindia/navigator/issues/29)
- [ ] [Event Ops](https://github.com/pythonindia/navigator/issues/30)
- [ ] [RnD](https://github.com/pythonindia/navigator/issues/31)
- [ ] [Volunteering](https://github.com/pythonindia/navigator/issues/32)

**Comment by ramlaxman** [comment]
Hi @Sc0rpi0n101 and @anistark,

I'd like to work on following tasks:
- [Call for proposals](https://github.com/pythonindia/navigator/issues/22)
- [Technology](https://github.com/pythonindia/navigator/issues/25)
