### ISSUE TITLE
Announcing 2nd Keynote

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024-tasks#42]
Announcing Lorena as the 2nd Keynote.
Announcement Date: May 29, 2024

## Tasks
- [x] Social Media Poster @iamaravindsekar
- [x] Social Media announcement @WatchfulHitman 
- [x] Blog post announcement @Sc0rpi0n101  
- [ ] Mailing list announcement  @sayanchowdhury  
- [x] Website update to display the first keynote speaker. @bhansa 

### Pre 4PM
- [x] Push a low resolution image to server to refer in website and blog @bhansa 
- [ ] Merge the blog post @Sc0rpi0n101 
- [x] Draft the social media announcement @WatchfulHitman  
- [ ] Merge the website changes @bhansa  

### Post 5PM
- [x] Deploy the blog and the website @bhansa  
- [x] Send the social media announcements out @WatchfulHitman  
- [ ] Announce on mailing list @sayanchowdhury 

### Communication Channel

- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [x] Social Media
  - [x]  Twitter
  - [x]  Linkedin
  - [x]  Mastodon
  - [x]  Instagram
  - [x]  Facebook

**Comment by anistark** [comment]
> I am @looooorencicole on insta and X (which I parked my X I just keep it) or the best one is mastodon @lorenanicole@mastodon.social. 

> The avatar and a random selfie is attached. 

![l1](https://github.com/pythonindia/inpycon2024-tasks/assets/5357586/4fc1c5b0-8df8-442c-87cd-9285084e5bd1)
![l2](https://github.com/pythonindia/inpycon2024-tasks/assets/5357586/7b7e620d-c2d8-44c5-b9de-08eaeb521f11)


Co-Organizer, PyLadies Chicago
Former Chair & Director, Python Software Foundation
www.lorenamesa.com
@loooorenanicole

**Comment by muralinmc** [comment]
If we have confirmed the speaker the same may be announced in SM as soon as possible as it may attract people to the conference

**Comment by anistark** [comment]
> If we have confirmed the speaker the same may be announced in SM as soon as possible as it may attract people to the conference

If you see the date, it's scheduled for 29th.

**Comment by harisibrahimkv** [comment]
# Mailing list & Blog
---------------------------

Introducing next among our Keynote Speakers for 2024!

She hails from the Moon, the Stars and the Cosmos!

That shouldn't be surprising when someone is a fan of both Star Wars & Star Trek and describes themselves as an explorer. However, while her training with light sabres and battles against the Borgs seem to have contributed to her becoming a Martial Artist, it only takes so much of her time that among many other things, she is a co-organizer of PyLadies Chicago as well.

The list of "many other things" that you can find on her website [1], truly is inspiring considering the one thing we all have in common as human beings, is a ticking clock. A lover of cats, a runner of marathons, you can see how "live long and prosper" is not just a dialogue from a series, but a motto that she lives and breaths by.

A firm believer of anti-racism, diversity & inclusion in technology, she is always happy to have a chat around any of these topics.

She is...

Loooorena Mesa!

A Former Chair & Director of the Python Software Foundation, we are enthralled and excited to have her as a Keynote Speaker at PyCon India this year.

Get to know her better at her website [1] and find her at her Mastodon [2].

[1] https://lorenamesa.com/index.html
[2] https://mastodon.social/@Lorenanicole

# Twitter
-----------
We have our next Keynote!

A Former Chair & Director of the Python Software Foundation, she is a co-organier of @PyLadiesChicago as well. Please welcome Lorena Mesa!

Join us for her keynote as well as this year's conference: konfhub.com/pyconindia2024

#PyconIndia2024

# Rest of 'em
------------------
And we have our next Keynote Speaker for 2024!
 
A die hard Star Wars & Star Trek fan who served as a former Chair & Director of the @ThePSF, she is a co-organier of @PyLadiesChicago as well. A firm believer of anti-racism, diversity & inclusion in technology who lives by the motto of "live long and prosper", please welcome Lorena Mesa!

A person with much knowledge and experience as well as a variety of interests, get to know more about her at https://lorenamesa.com/.

Grab your PyCon India tickets at konfhub.com/pyconindia2024. Join us the for the amazing conference this is shaping up to be.

**Comment by WatchfulHitman** [comment]
2 doubts:

1. @anistark can we tag psf and pyladieschicago in this post from our social media handles since Lorena Mesa represents them
2.  @anistark can we change the ticket link of konfhub to the pycon website link as it gets reported on Fb and Insta

**Comment by bhansa** [comment]
Which photo is to be used for website ?

- Used the animated one.

**Comment by anistark** [comment]
@Sc0rpi0n101 blog is not deployed ?
