### ISSUE TITLE
[Communications] Announce the mentorship call

### ISSUE THREAD

**Issue by bhavin192** [pythonindia/inpycon2024-tasks#43]
Aim is to announce the mentorship call, this is aimed towards the folks who are planning to submit a talk proposal, but have some doubts or need any help with it. 

The message/announcement should include this form: https://forms.gle/C2YvdqZSzo7Tdnft7
Call link: https://meet.jit.si/PyConIndia24Mentorship (skip this from the announcement, but we should have it in the messages on 26th). 

Some examples from 2021, this time we want people to fillout the form so we get an idea about folks joining in:
- https://x.com/pyconindia/status/1388069740015280128
- https://x.com/pyconindia/status/1388397009690783745
- https://x.com/pyconindia/status/1389919480004845568
- https://x.com/pyconindia/status/1393502070582304768

Announcement Date: 24th May, 2024
Timing of the call: 26th May at 15:00 IST.

## Tasks
- [ ] Announce on all social media
- [ ] Add a note about this call in the next CFP related email (see below).

## Timeline
- Initial announcement 24th May.
- Another note along with CFP reminder on Saturday 25th.
- One or two reminders on the day of mentorship call i.e. before 26th 15:00 IST. 

### Communication Channel (if needed for your task)

This can go with the next CFP related email, let's coordinate that over Zulip. I guess the next mail would be about the extension, so we can add upcoming Sunday in that mail. 
- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups

- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

@WatchfulHitman

**Comment by anistark** [comment]
Guess this is done. @bhavin192  feel free to reopen if anything pending.
