### ISSUE TITLE
BoFs and Posters CFP Announcement

### ISSUE THREAD

**Issue by wavicles** [pythonindia/inpycon2024-tasks#47]
Scheduled for **11th June, 2024 Time: 6:00pm**

## Tasks
- [ ] [Junction setup for BoFs and Posters 2024](add link here) @wavicles 
- [ ] Prepare a blog post  @wavicles @Sc0rpi0n101 
- [ ] Prepare the content for the social media post, along with the picture   @Sc0rpi0n101
- [ ] Social media announcement @WatchfulHitman
- [ ] Mailing list announcement  @WatchfulHitman

### Pre 4 PM
- [ ] Set up Junction for CFP 2024 @wavicles 
- [ ] Verify the contents of Junction @anistark 
- [ ] Merge the blog post
- [ ] Draft the social media announcement  @WatchfulHitman
- [ ] Add a link on the main website  

### Post 5 PM
- [ ] Deploy the blog on the website @palnabarun 
- [ ] Send the social media announcements out  @WatchfulHitman
- [ ] Announce on mailing list  @WatchfulHitman
- [ ] Send to other Python Mailing lists @WatchfulHitman

### Communication Channels

- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by wavicles** [comment]
here is the doc for blog post. At the end I have added sample social media messages.
https://docs.google.com/document/d/1HV0qqaWAy5oUZwyP608paHIvBqHq4c3eT1Y0YNT2EI4/edit?usp=sharing

**Comment by anistark** [comment]
Guess this is done. @wavicles feel free to reopen if anything pending.
