### ISSUE TITLE
Announce 3rd Keynote speaker

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2024-tasks#48]
Announcing James Powell as the 2nd Keynote.
Announcement Date: June 28th, 2024

## Tasks
- [ ] Social Media Poster @iamaravindsekar
- [ ] Social Media announcement @WatchfulHitman 
- [ ] Blog post announcement @Sc0rpi0n101  
- [ ] Mailing list announcement  @sayanchowdhury  
- [ ] Website update to display the first keynote speaker. @bhansa 

### Pre 4PM
- [ ] Push a low resolution image to server to refer in website and blog @bhansa 
- [ ] Merge the blog post @Sc0rpi0n101 
- [ ] Draft the social media announcement @WatchfulHitman  
- [ ] Merge the website changes @bhansa  

### Post 5PM
- [ ] Deploy the blog and the website @bhansa  
- [ ] Send the social media announcements out @WatchfulHitman  
- [ ] Announce on mailing list @sayanchowdhury 

### Communication Channel

- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by sayanchowdhury** [comment]
James Powell is a professional Python programmer and enthusiast. He
started working with Python in the finance industry building reporting
and analysis systems for prop trading front offices. He currently
works as a consultant building data engineering and scientific
computing platforms for a wide-range of clients using cutting-edge
open source tools like Python and React. He also offers a variety of
corporate training courses and coaching sessions in all areas of
Python.

In his spare time, he serves on the board of NumFOCUS as co-Chairman
and Vice President. NumFOCUS is the 501(c)(3) non-profit that supports
all the major tools in the Python data analysis ecosystem (incl.
pandas, numpy, jupyter, matplotlib, and others.) At NumFOCUS, he helps
build global open source communities for data scientists, data
engineers, and business analysis. He helps NumFOCUS run the PyData
conference series and has sat on speaker selection and organizing
committees for over two dozen conferences. James is also a prolific
speaker: since 2013, he has given over seventy conference talks at
over fifty Python events worldwide.

**Comment by sayanchowdhury** [comment]
![2020 - JP Headshot](https://github.com/pythonindia/inpycon2024-tasks/assets/500628/18302e41-af7f-4599-aa67-707558e38e0c)
