### ISSUE TITLE
[Comms] Post Review for 1st Platinum Sponsor

### ISSUE THREAD

**Issue by WatchfulHitman** [pythonindia/inpycon2024-tasks#49]
**Content**
🎉Exciting News! We are proud to announce happyfox as our first Platinum Sponsor for #PyConIndia2024

#sponsor #conference #bengaluru

**POSTER**
![Platinum Sponsor1](https://github.com/user-attachments/assets/6eb24c10-7608-4c0a-a74a-62e39545d65d)

Announcement Date: 19th July and 5:00 pm, 2024

## Tasks
- [ ] blogpost, @Sc0rpi0n101 
- [ ] review of the post content by @rayandas , @sayanchowdhury , @palnabarun , @kalyan678
- [ ] website update to display first platinum sponsor @bhansa 

## Timeline
- [ ] 19th July,2024
- [ ] 19th July,2024 1 pm 
- [ ] 19th July,2024 4:30 pm

**Comment by sayanchowdhury** [comment]
- Should be HappyFox, not happyfox. Please correct. 
- Poster has "Welcome" capitalized.
- Blog needs to be linked in the tweet.
- HappyFox needs to be tagged in tweet or Image.

**Comment by abhishekmishragithub** [comment]
@WatchfulHitman please wait till the blog, we need to add the url of the blog in the post as well.
here is the issue to create the blog: https://github.com/pythonindia/inpycon-blog/issues/453
@Sc0rpi0n101 can you please do it before 19th july, 1 PM ?

**Comment by Sc0rpi0n101** [comment]
@abhishekmishragithub I've created a PR for the blog: https://github.com/pythonindia/inpycon-blog/pull/454

Please review

**Comment by abhishekmishragithub** [comment]
@bhansa can we add the platinum sponsor section and add HappyFox under it? T
this issue has all the details. https://github.com/pythonindia/inpycon-blog/issues/453

**Comment by WatchfulHitman** [comment]
**Content**
🎉Exciting News! We are proud to announce HappyFox(tag) as our first Platinum Sponsor for #PyConIndia2024. Read more in our blog - <LINK>

#sponsor #conference #bengaluru

@sayanchowdhury looks good !!

**Comment by WatchfulHitman** [comment]
**MAIL CONTENT**

Hi All,

We are excited to announce our 1st Platinum Sponsor for PyCon India 2024 -
HappyFox Inc. We invite you to learn more about them: - 

“*HappyFox Inc*
HappyFox is a leading provider of AI-driven support solutions, committed to exceptional customer and employee experiences. Their products include Help Desk, Service Desk, Assist AI, Workflows, Live Chat, Chatbot, and Business Intelligence. New Product Update: HappyFox AI enhances support operations with AI Copilot, AI Insights, AI Knowledge Base, AI Resolve, and AI Agents. HappyFox is trusted by over 2,000 companies in 70+ countries and empowering support teams in customer service, IT, HR, facilities, and more with user-friendly solutions that simplify complexity and encourage collaboration.
Follow them on their social media channels [0],[1] [2] [3] and read more on their website [4].

We are immensely grateful to HappyFox Inc for their generous support. Stay tuned
for more exciting updates!

[0] https://www.instagram.com/happyfoxapp?igsh=MW5vMWswbXlxbG1qeg==
[1] https://www.facebook.com/happyfoxapp/
[2] https://x.com/HappyFoxApp
[3] https://www.linkedin.com/company/happyfox-inc-/
[4] https://happyfox.com

Best Regards
<name>
On Behalf of PyCon India Team

**Comment by anistark** [comment]
Looks good. Check on formatting and open quote. 

Just mentioning numbers doesn't look good. Can do like Instagram[0], Faceboook[1], ... so on.

The instagram link get rid of `igsh` param?

**Comment by WatchfulHitman** [comment]
Thanks a lot @anistark . Here's the updated one

Hi All,

We are excited to announce our 1st Platinum Sponsor for PyCon India 2024 -
HappyFox Inc. We invite you to learn more about them: - 

“HappyFox Inc"
HappyFox is a leading provider of AI-driven support solutions, committed to exceptional customer and employee experiences. Their products include Help Desk, Service Desk, Assist AI, Workflows, Live Chat, Chatbot, and Business Intelligence. New Product Update: HappyFox AI enhances support operations with AI Copilot, AI Insights, AI Knowledge Base, AI Resolve, and AI Agents. HappyFox is trusted by over 2,000 companies in 70+ countries and empowering support teams in customer service, IT, HR, facilities, and more with user-friendly solutions that simplify complexity and encourage collaboration.
Follow them on their social media channels Instagram [0], Facebook [1], X [2], LinkedIn [3] and read more on their website [4].

We are immensely grateful to HappyFox Inc for their generous support. Stay tuned
for more exciting updates!

[0] https://www.instagram.com/happyfoxapp
[1] https://www.facebook.com/happyfoxapp/
[2] https://x.com/HappyFoxApp
[3] https://www.linkedin.com/company/happyfox-inc-/
[4] https://happyfox.com/

Best Regards
<name>
On Behalf of PyCon India Team

**Comment by anistark** [comment]
Should we also add our own blog and X post announcement links here too?

**Comment by WatchfulHitman** [comment]
Hi All,

We are excited to announce our 1st Platinum Sponsor for PyCon India 2024 - HappyFox Inc. 

HappyFox Inc
------------
HappyFox is a leading provider of AI-driven support solutions, committed to exceptional customer and employee experiences. Their products include Help Desk, Service Desk, Assist AI, Workflows, Live Chat, Chatbot, and Business Intelligence. New Product Update: HappyFox AI enhances support operations with AI Copilot, AI Insights, AI Knowledge Base, AI Resolve, and AI Agents. HappyFox is trusted by over 2,000 companies in 70+ countries and empowering support teams in customer service, IT, HR, facilities, and more with user-friendly solutions that simplify complexity and encourage collaboration.

Follow them on their social media channels Instagram[0], Facebook[1], X[2], LinkedIn[3] and read more on their website[4].

We are immensely grateful to HappyFox Inc for their generous support. 

Feel free to share the announcement blog post[5] in your network.

Stay tuned for more exciting updates!

[0] https://www.instagram.com/happyfoxapp
[1] https://www.facebook.com/happyfoxapp/
[2] https://x.com/HappyFoxApp
[3] https://www.linkedin.com/company/happyfox-inc-/
[4] https://happyfox.com/
[5] https://in.pycon.org/blog/2024/sponsor-announcement-happyfox.html

Best Regards
<name>
On Behalf of PyCon India Team
