### ISSUE TITLE
[Comms] Review of Content for 2nd Platinum Sponsor Post

### ISSUE THREAD

**Issue by WatchfulHitman** [pythonindia/inpycon2024-tasks#51]
**Content**

🎉Exciting News! We are excited to announce Abnormal Security(tag) as our second Platinum Sponsor for 🐍#PyConIndia2024. Read more in our blog - [LINK]

#sponsor #conference #bengaluru #platinum

![Platinum Sponsor2](https://github.com/user-attachments/assets/805b3bfe-5e90-4586-b846-81164743ac10)

MAIL CONTENT:

**Subject**:  2nd Platinum Sponsor for PyCon India 2024

Hi All,

We are excited to announce Abnormal Security as our second Platinum Sponsor for PyCon India 2024.

 Abnormal Security is the #1 AI-Native Platform for Human Behavior Security and one of the world’s fastest growing cybersecurity companies. They leverage AI-native technology to keep their customers and people safe, by stopping threats that exploit human behavior. With a fundamentally different approach to cloud email security, they are building a generational company. They deeply understand human behavior to detect anomalies, protect against cloud account takeovers, and prevent breaches such as phishing attacks and socially-engineered threats. Their API-based platform extends unprecedented protection to consistently lower cyber risk. Their engineering teams globally have a culture centered around excellence and mastery, to solve crucial cybersecurity problems for enterprises worldwide. Their India center is growing and offers the opportunity to work with high-caliber teams and have high-value impact with industry-leading technology. 

Follow them on their social media channels: X [0], LinkedIn [1] and read more on their website [2].
 
We are immensely grateful to Abnormal Security for their generous support.

Feel free to share the announcement blog post [3] in your network.

Stay tuned for more exciting updates!
         
[0] https://x.com/AbnormalSec
[1] https://www.linkedin.com/company/abnormalsecurity/
[2] https://abnormalsecurity.com/
[3] [LINK]

Best Regards
<NAME>
On Behalf of PyCon India Team

Announcement Date: 24th July 5:00 PM, 2024

## Tasks
- [x] Review of the above social media content and mail content, @rayandas @sayanchowdhury @palnabarun @kalyan678
- [x] Blog about the 2nd Platinum Sponsor, @Sc0rpi0n101 
- [x] Publishing the blog on the website @bhansa 
- [x] Social Media Post @WatchfulHitman 

### Pre 4PM
- [x] Review of the above social media content and mail content, @rayandas @sayanchowdhury @palnabarun @kalyan678
- [x] Blog about the 2nd Platinum Sponsor, @Sc0rpi0n101 
- [x] Publishing the blog on the website @bhansa

### Post 5PM
- [x] Social Media Post, @WatchfulHitman 

### Communication Channel (if needed for your task)

- [x] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by kalyan678** [comment]
@WatchfulHitman - I think the first line should look like this - We are excited to announce Abnormal Security as our second Platinum Sponsor for PyCon India 2024.

**Comment by sayanchowdhury** [comment]
What was the subject for the first announcement?

**Comment by WatchfulHitman** [comment]
Announcing our 1st Platinum Sponsor for PyCon India 2024 - HappyFox Inc

**Comment by sayanchowdhury** [comment]
Then we should have the subject for this one "Subject: Announcing our 2nd Platinum Sponsor for PyCon India 2024 - Abnormal Security"

**Comment by WatchfulHitman** [comment]
Okay will do that.

**Comment by WatchfulHitman** [comment]
So can we go ahead with it. @sayanchowdhury

**Comment by sayanchowdhury** [comment]
Can you please update the content?

**Comment by sayanchowdhury** [comment]
> Follow them on their social media channels X [0], LinkedIn [1] and read more on their website [2].

Follow them on their social media channels: X [0], LinkedIn [1] and read more on their website [2].

**Comment by harisibrahimkv** [comment]
Looks good to me. Was the write up they provided themselves?

**Comment by WatchfulHitman** [comment]
> Looks good to me. Was the write up they provided themselves?

yes just made the we,I to they and Our to their

**Comment by WatchfulHitman** [comment]
> > Follow them on their social media channels X [0], LinkedIn [1] and read more on their website [2].
> 
> Follow them on their social media channels: X [0], LinkedIn [1] and read more on their website [2].

Incorporated the changes
