### ISSUE TITLE
Announcing Usha Rengaraju as the 3rd Keynote.

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2024-tasks#53]
Announcing Usha Rengaraju as the 2nd Keynote.
Announcement Date: July 27th, 2024

## Tasks
- [ ] Social Media Poster @iamaravindsekar
- [ ] Social Media announcement @WatchfulHitman 
- [ ] Blog post announcement @Sc0rpi0n101  
- [ ] Mailing list announcement  @WatchfulHitman 
- [ ] Website update to display the first keynote speaker. @bhansa 

### Pre 4PM
- [ ] Push a low resolution image to server to refer in website and blog @bhansa 
- [ ] Merge the blog post @Sc0rpi0n101 
- [ ] Draft the social media announcement @WatchfulHitman  
- [ ] Merge the website changes @bhansa  

### Post 5PM
- [ ] Deploy the blog and the website @bhansa  
- [ ] Send the social media announcements out @WatchfulHitman  
- [ ] Announce on mailing list @WatchfulHitman 

### Communication Channel

- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by sayanchowdhury** [comment]
Usha is an AI consultant and corporate trainer and she is the World’s first women triple Kaggle Grandmaster .She specializes in Deep Learning , Generative AI , TigerGraph and Probabilistic Graphical Models and was also one of the judges of Tiger Graph “ Graph for all - Million Dollar Challenge” in 2022 and the judge for Intel oneAPI Hackathon organized by Intel software in 2022 .

She is ranked as top ten Data Scientists in India for the year 2020 by Analytics India Magazine , ranked as top ten women data scientists by Analytics Insight magazine for 2021 and also ranked as top 150 AI Leaders and Influencers by 3AI magazine.

She organized NeuroAI which is India’s first-ever research symposium in the interface of Neuroscience and Data Science. She also organized the Neurodiversity India Summit which is India’s first ever conference in Neurodiversity . 

She is one of the winners of “ML in Action” competition organized by the ML Developer programs team at Google and her team won first place in WiDS 2022 Datathon organized by Stanford University . She is also the winner of Kaggle ML Research spotlight for 2022 and winner of TensorFlow Community Spotlight 2023 .

**Comment by iamaravindsekar** [comment]
Can we get a shorter bio for the speaker which is good enough to use on our digital creatives?

**Comment by sayanchowdhury** [comment]
Ack. Requested

**Comment by bhansa** [comment]
Can we also have a title for speaker as in, "Director at XYZabs"etc.

**Comment by sayanchowdhury** [comment]
Yes, I have requested but I have got no response yet. I will followup

**Comment by WatchfulHitman** [comment]
can we get a picture of her for posting in the social media

**Comment by sayanchowdhury** [comment]
![Usha](https://github.com/user-attachments/assets/e0a3130b-e56b-43f4-9b20-b19411f4ea27)

Here is the picture to be used.
Bio: Usha Rengaraju, Chief of Research, Exa Protocol, Autism Advocate

**Comment by WatchfulHitman** [comment]
**Change in announcement date : 10th August 2024** 
@sayanchowdhury @Sc0rpi0n101 @iamaravindsekar @bhansa

**Comment by WatchfulHitman** [comment]
poster of the same 
![Usha Rengaraju - Keynote Speaker](https://github.com/user-attachments/assets/39fb30d7-07b7-42fb-9007-ef0c7672fe31)

**Comment by Sc0rpi0n101** [comment]
I've created a PR for the blog: https://github.com/pythonindia/inpycon-blog/pull/457

Please review. Also, please let me know if we have any social media handles or any website for her
CC: @sayanchowdhury

**Comment by harisibrahimkv** [comment]
Here's an edited version: https://github.com/pythonindia/inpycon-blog/pull/457#discussion_r1712891526

**Comment by WatchfulHitman** [comment]
Hi @Sc0rpi0n101, @harisibrahimkv  can I get the social media content and mail content for posting the same

**Comment by harisibrahimkv** [comment]
Email Content
===========
Hello hello!

Hope all y'all are having a good weekend! With that sheer optimism and even more excitement, please allow us to contribute a little more it. Announcing our next keynote speaker for PyCon India 2024...

*Drum roll please*

Usha Rengaraju!

Trying to describe Usha's achievements and contributions to the ML world wouldn't do it justice. That itself should give you a little glimpse into the person she is.

She served as a judge for multiple Hackathons and challenges over the years, is recognised by multiple magazines around the world as one among the best Data Scientists around and is involved in organising multiple events such NeuroAI & Neurodiversity India Summit.

She inspires us not just as someone who worked hard to get to where she is. But more importantly as someone who strives to consistently maintain her expertise and involvement in her field as well by competing and winning multiple challenges such Kaggle ML Research spotlight & WiDS 2022 Datathon just to name a few.

Do read more about her at our blog: <insert link>

It goes without saying that we feel privileged to have her as a Keynote this year at PyCon India and we hope all of you get to interact with her and learn from her experience.

With love and excitement,
The PyCon India Team.

**Comment by harisibrahimkv** [comment]
Twitter
=====
And proudly announcing the next milestone in our attempts at bringing the masters of their crafts to PyCon India 2024...

Our next keynote speaker - Usha Rengaraju!

She is the Chief of Research at Exa Protocol & an Autism Advocate.

Read more about her at our blog:

**Comment by harisibrahimkv** [comment]
Other Social Media
===============
Proudly announcing the next milestone in our attempts at bringing the masters of their crafts to PyCon India 2024...

Our next keynote speaker - Usha Rengaraju!

Among many other things, she is the Chief of Research at Exa Protocol & an Autism Advocate. Her achievements and recognitions go beyond what we are able to capture in words. However, we've tried our best to. Do read about her myriad of experiences from being a judge at various events to organising multiple conferences to how she manages to consistently be at the top of her game & maintain her skills by visiting our blog about her at: 

With a whole lot of excitement (and just a month's worth of prep left),
The PyCon India Team.

**Comment by WatchfulHitman** [comment]
> # Email Content
> Hello hello!
> 
> Hope all y'all are having a good weekend! With that sheer optimism and even more excitement, please allow us to contribute a little more it. Announcing our next keynote speaker for PyCon India 2024...
> 
> _Drum roll please_
> 
> Usha Rengaraju!
> 
> Trying to describe Usha's achievements and contributions to the ML world wouldn't do it justice. That itself should give you a little glimpse into the person she is.
> 
> She served as a judge for multiple Hackathons and challenges over the years, is recognised by multiple magazines around the world as one among the best Data Scientists around and is involved in organising multiple events such NeuroAI & Neurodiversity India Summit.
> 
> She inspires us not just as someone who worked hard to get to where she is. But more importantly as someone who strives to consistently maintain her expertise and involvement in her field as well by competing and winning multiple challenges such Kaggle ML Research spotlight & WiDS 2022 Datathon just to name a few.
> 
> Do read more about her at our blog:
> 
> It goes without saying that we feel privileged to have her as a Keynote this year at PyCon India and we hope all of you get to interact with her and learn from her experience.
> 
> With love and excitement, The PyCon India Team.

Does "_Drum roll please_" have to be in italics in email as well ?

**Comment by harisibrahimkv** [comment]
Ha ha, nope. I put it like `*Drum roll please*`.

**Comment by WatchfulHitman** [comment]
> Ha ha, nope. I put it like `*Drum roll please*`.

Cool

**Comment by harisibrahimkv** [comment]
@WatchfulHitman Do remember to add our blog post's link wherever I've left space for it.

**Comment by WatchfulHitman** [comment]
> @WatchfulHitman Do remember to add our blog post's link wherever I've left space for it.

Yes will do but the pr hasn't been merged & deployed yet

**Comment by harisibrahimkv** [comment]
I guess @Sc0rpi0n101 will have to do that.

**Comment by WatchfulHitman** [comment]
The post has been completed.
