### ISSUE TITLE
[Comms] Announce IndeeTV Sponsor

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024-tasks#56]
Announce IndeeTV as Silver Sponsor

Announcement Date: Aug 12th, 2024

## Tasks
- [ ] Writen Content, @Sc0rpi0n101 
- [ ] Poster/Graphic, @iamaravindsekar
- [x] Website, @bhansa 

### Pre 4PM
- [ ] Mail Content
- [ ] Posters/Graphics
- [ ] Social Media Content
- [x] Website PR

### Post 5PM
- [x] Deploy Website
- [ ] Post on In-PyCon Mailing List
- [ ] Post on Social Media
- [ ] X-Post on other mailing lists

### Communication Channel (if needed for your task)

- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by WatchfulHitman** [comment]
**Social Media Post**

🎉 Exciting news! We’re thrilled to announce that Indee TV(tag) is our second Silver Sponsor for 🐍#PyConIndia2024. Learn more on our blog - [LINK]

#sponsor #conference #bengaluru #silver

**Mail Content**

**Subject** : Announcing 2nd Silver Sponsor for PyCon India 2024

Hi Everyone,
     
We are excited to announce our 2nd Silver Sponsor for PyCon India 2024 - Indee TV. 

Indee TV is a leading provider of secure video platforms for the entertainment industry. They focus on innovation, security, accessibility, and user experience, offering comprehensive solutions for screener submission, content management, secure viewing, and analytics. Netflix, Amazon, Showtime, Paramount Pictures, NBCU, and over 700 other entertainment companies trust Indee TV to screen their content securely.

Follow them on their social media channels X [0], LinkedIn [1] and read more on their website [2].

We are immensely grateful to Indee TV for their generous support.

Feel free to share the announcement blog post [3] in your network.

Stay tuned for more exciting updates!

[0] https://x.com/indee
[1] https://www.linkedin.com/company/indee.tv/
[2] https://indee.tv/
[3] [LINK]

Best Regards
<NAME>
On Behalf of PyCon India Team

**POSTER** : 
![Silver Sponsor-Indee](https://github.com/user-attachments/assets/ba457d03-5b2a-48c5-a5a0-c7c9545b767b)

**Logo for Blog**: 
![Indee-Powerbank-Decal-Design-v2 - Sheesh Mohsin](https://github.com/user-attachments/assets/f3bfaa68-84dd-42d5-ad67-4465807320fd)

**Comment by WatchfulHitman** [comment]
> **Social Media Post**
> 
> 🎉 Exciting news! We’re thrilled to announce that Indee TV(tag) is our second Silver Sponsor for 🐍#PyConIndia2024. Learn more on our blog - [LINK]
> 
> #sponsor #conference #bengaluru #silver
> 
> **Mail Content**
> 
> **Subject** : Announcing 2nd Silver Sponsor for PyCon India 2024
> 
> Hi Everyone,
> 
> We are excited to announce our 2nd Silver Sponsor for PyCon India 2024 - Indee TV.
> 
> Indee TV is a leading provider of secure video platforms for the entertainment industry. They focus on innovation, security, accessibility, and user experience, offering comprehensive solutions for screener submission, content management, secure viewing, and analytics. Netflix, Amazon, Showtime, Paramount Pictures, NBCU, and over 700 other entertainment companies trust Indee TV to screen their content securely.
> 
> Follow them on their social media channels X [0], LinkedIn [1] and read more on their website [2].
> 
> We are immensely grateful to Indee TV for their generous support.
> 
> Feel free to share the announcement blog post [3] in your network.
> 
> Stay tuned for more exciting updates!
> 
> [0] https://x.com/indee [1] https://www.linkedin.com/company/indee.tv/ [2] https://indee.tv/ [3] [LINK]
> 
> Best Regards On Behalf of PyCon India Team
> 
> **POSTER** : ![Silver Sponsor-Indee](https://private-user-images.githubusercontent.com/20946624/356696224-ba457d03-5b2a-48c5-a5a0-c7c9545b767b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjUwMzUsIm5iZiI6MTcyMzIyNDczNSwicGF0aCI6Ii8yMDk0NjYyNC8zNTY2OTYyMjQtYmE0NTdkMDMtNWIyYS00OGM1LWE1YTAtYzdjOTU0NWI3NjdiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDE3MzIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZjE5N2I4MWUxYmFiNDg0YjdmZWY3ZmRjMDRkZjQ2OWYzMGI3NWNmNDNjMmExODRkZTk3YWY3OTE3YTdiY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iAiNlgA2cAneG8l7sfxr5-9AQHpQ5neA4IRsMDgc300)
> 
> **Logo for Blog**: ![Indee-Powerbank-Decal-Design-v2 - Sheesh Mohsin](https://private-user-images.githubusercontent.com/20946624/356697007-f3bfaa68-84dd-42d5-ad67-4465807320fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjUwMzUsIm5iZiI6MTcyMzIyNDczNSwicGF0aCI6Ii8yMDk0NjYyNC8zNTY2OTcwMDctZjNiZmFhNjgtODRkZC00MmQ1LWFkNjctNDQ2NTgwNzMyMGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDE3MzIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNzBjYjVkMTk5OTY0ODYxNGY3OTQxNTY4Zjc4YTA4MmVjZmI0MTVjOWRjNThhNzQwMzhiNDlhZjgwY2U0NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XU3246F8amanIYN6DH7AAkHf8ScJKcyggkJQhpsUxbQ)

Please review @sayanchowdhury @rayandas @kalyan678 @palnabarun

**Comment by anistark** [comment]
Some suggestions:

Social Media:

"is our second" -> "as"
Add one line about IndeeTv too, then mention to read more on blog maybe?

Mail:

"our 2nd" -> "" (lets avoid using index here)

**Comment by WatchfulHitman** [comment]
This post went through
