### ISSUE TITLE
[Comms] Announce WSO2 Sponsor

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024-tasks#57]
Announce WSO2 as Platnum Sponsor

Announcement Date: Aug 14th, 2024

## Tasks
- [ ] Writen Content, @Sc0rpi0n101 
- [ ] Poster/Graphic, @iamaravindsekar
- [ ] Website, @bhansa 

### Pre 4PM
- [ ] Mail Content
- [ ] Posters/Graphics
- [ ] Social Media Content
- [ ] Website PR

### Post 5PM
- [ ] Deploy Website
- [ ] Post on In-PyCon Mailing List
- [ ] Post on Social Media
- [ ] X-Post on other mailing lists

### Communication Channel (if needed for your task)

- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook
