### ISSUE TITLE
[Comms] Announce TuneAI Sponsor

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024-tasks#58]
Announce TuneAI as Gold Sponsor

Announcement Date: Aug 17th, 2024

## Tasks
- [ ] Writen Content, @Sc0rpi0n101 
- [ ] Poster/Graphic, @iamaravindsekar
- [ ] Website, @bhansa 

### Pre 4PM
- [ ] Mail Content
- [ ] Posters/Graphics
- [ ] Social Media Content
- [ ] Website PR

### Post 5PM
- [ ] Deploy Website
- [ ] Post on In-PyCon Mailing List
- [ ] Post on Social Media
- [ ] X-Post on other mailing lists

### Communication Channel (if needed for your task)

- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by WatchfulHitman** [comment]
**Logo**: 
<img width="758" alt="Primary Logo (Dark Pruple with Orange) with Padding - Naman Maheshwari" src="https://github.com/user-attachments/assets/b67a9422-596c-4c93-9026-abcbd51f43c1">


**Poster** :  
![Gold Sponsor-Tune](https://github.com/user-attachments/assets/6ad1d125-889f-4b2c-8eb0-b748d36f265e)

**Mail Content**

**Subject**: 1st Gold Sponsor for PyCon India 2024

Hi Everyone,

We are excited to announce our 1st Gold Sponsor for PyCon India 2024 - Tune AI.

Tune AI empowers developers with a toolkit to turn AI ideas into apps - harnessing both closed and open source LLMs for projects ranging from side hustles and hobbies to enterprise-grade use-cases.

Follow them on their social media channels X[0], LinkedIn[1], Instagram[2] and read more on their website[3].
We are immensely grateful to Tune AI for their generous support.

Feel free to share the announcement blog post[4] in your network.

Stay tuned for more exciting updates!

[0] https://x.com/tunehq_ai	
[1] https://www.linkedin.com/company/tuneai
[2] https://www.instagram.com/tune.app
[3] http://www.tunehq.ai/
[4] [LINK]

Best Regards,

On Behalf of PyCon India Team

**Social Media Post**

🎉 Exciting news! We’re thrilled to announce that Tune AI is our first Gold Sponsor for 🐍#PyConIndia2024. 

Learn more on our blog - [LINK]

#gold #sponsor #conference

**Risepad link**: https://pad.riseup.net/p/gLkZx4aRfvX8SVbfFUNA

**Comment by rayandas** [comment]
Please update the social media post from ‘Gold Sponsor for 🐍#PyConIndia2024.’ 
to
‘Gold Sponsor for #PyConIndia2024. 🐍’

**Comment by anistark** [comment]
Made some edits on risepad. @rayandas please review again. Let's not use index as discussed before. No need for 1st, 2nd, ...
