### ISSUE TITLE
Schedule Announcement

### ISSUE THREAD

**Issue by muralinmc** [pythonindia/inpycon2024-tasks#59]
Describe your task need and goal here

Announcement Date: <15th August>, 2024

## Tasks
- [x] preparing the schedule
- [x] design the schedule,<@iamaravindsekar>
- [x] publish the same in website, <@bhansa>

### Pre 4PM
- [ ] <TASK>, <ASSIGNEE>

### Post 5PM
- [ ] <TASK>, <ASSIGNEE> 

### Communication Channel (if needed for your task)

- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by bhavin192** [comment]
cc @WatchfulHitman as this involves comms work to announce the schedule on SM and mailing lists. 
Blog post is **not** required.
