### ISSUE TITLE
[Comms] Announcing next Platinum Sponsor Choreo by WSO2

### ISSUE THREAD

**Issue by WatchfulHitman** [pythonindia/inpycon2024-tasks#61]
Review Content:

**Social Media Post**

🎉 We’re thrilled to announce our next Platinum Sponsor for 🐍#PyConIndia2024, Choreo by WSO2 [TAG] 

Choreo is a powerful internal developer platform as a service designed for developers

Learn more on our blog - [LINK]

#sponsor #platinum

**Mailing Content**

Subject: Announcing the next Platinum Sponsor for PyCon India 2024

Hi Everyone,
     
We are excited to announce our next Platinum Sponsor for PyCon India 2024 - Choreo by WSO2

Choreo is a powerful internal developer platform as a service designed for developers. It streamlines the deployment, monitoring, and management of cloud-native applications, allowing developers to focus on innovation and writing efficient code. Simply connect your code and have it deployed in minutes, ensuring rapid integration and deployment to enhance productivity and streamline your workflow.

What Choreo Offers:
1) Choreo's Python buildpack streamlines the deployment process for all application types.
2) Streamline development with automated deployments.
3) Ensure your Flask services are secure with Choreo's robust authentication and authorization mechanisms.
4) Choreo's VS Code plugin empowers you to build, deploy, and test your Django applications directly from your IDE.
5) Seamlessly facilitates horizontal scaling.
6) Enables you to provision databases with ease, saving you time and effort.
7) Gain deep insights into your Python apps with Choreo's logging and observability metrics.

Follow them on their social media channels X[0], LinkedIn[1] and read more on their website[2].

We are immensely grateful to Choreo by WSO2 for their generous support.

Feel free to share the announcement blog post[3] in your network.

Stay tuned for more exciting updates!

[0] https://x.com/ChoreoDev
[1] https://www.linkedin.com/company/wso2/posts/?feedView=all
[2] https://choreo.dev/?utm_source=Conferen&utm_medium=link&utm_campaign=Conferen_link_pyconindia_conference_240815
[3] [LINK]

Best Regards
<NAME>
On Behalf of PyCon India Team

**Riseup Pad Link:** https://pad.riseup.net/p/yBRh3bQnvxUUpN7PufbL

**Poster** : 
![Platinum Sponsor-Choreo](https://github.com/user-attachments/assets/75313d5e-f680-43bc-9448-8a655a4ddea4)

**Logo**:
 ![choreo-by-wso2-black - HotJar Choreo](https://github.com/user-attachments/assets/28230ed4-11ff-4ca5-8813-9e5b07bf9d03)

Announcement Date: 24 August 5:00 pm, 2024

## Tasks
- [ ] Review of content, @sayanchowdhury @rayandas @palnabarun @Sc0rpi0n101 @harisibrahimkv
- [ ] Blog Creation, @Sc0rpi0n101
- [ ]  Posting of blog on website, @bhansa
- [ ]  Poster Creation, @iamaravindsekar

### Pre 4PM
- [ ] Review of content, @sayanchowdhury @rayandas @palnabarun @Sc0rpi0n101 @harisibrahimkv
- [ ] Blog Creation, @Sc0rpi0n101
- [ ]  Posting of blog on website, @bhansa
- [ ]  Poster Creation, @iamaravindsekar

### Post 5PM
- [ ] posting content and mailing, @WatchfulHitman @tankala 

### Communication Channel (if needed for your task)

- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by anistark** [comment]
duplicate? #57
