### ISSUE TITLE
[Comms] Next Silver Sponsor Bloomberg

### ISSUE THREAD

**Issue by WatchfulHitman** [pythonindia/inpycon2024-tasks#63]
Review the content:

Riseup Pad: https://pad.riseup.net/p/ahVMFNOcL1o7FzoIaze4

Logo: 
![BBGEngineering_black - Cathy Hom](https://github.com/user-attachments/assets/9d9f1431-cf4c-4422-b794-ac125a52368f)

## Tasks
- [ ] Review of content, @sayanchowdhury @rayandas @palnabarun @Sc0rpi0n101 @harisibrahimkv
- [ ]  Blog Creation, @Sc0rpi0n101 
- [ ] Posting of blog on website, @bhansa 
- [ ] Poster Creation, @iamaravindsekar

### Pre 4PM
- [ ] Review of content, @sayanchowdhury @rayandas @palnabarun @Sc0rpi0n101 @harisibrahimkv
- [ ]  Blog Creation, @Sc0rpi0n101 
- [ ] Posting of blog on website, @bhansa 
- [ ] Poster Creation, @iamaravindsekar

### Post 5PM
- [ ] posting content and mailing, @WatchfulHitman @tankala 

### Communication Channel (if needed for your task)

- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by iamaravindsekar** [comment]
Please find the poster in the shared drive url, Thank you

https://drive.google.com/file/d/1e3TTsnimMwyCySSeiEXfYacWjVgGS8s2/view?usp=sharing

**Comment by palnabarun** [comment]
@WatchfulHitman @Sc0rpi0n101 The following content is now approved for publishing.

### Social

🎉 We’re thrilled to announce our next Silver Sponsor for 🐍#PyConIndia2024, Bloomberg [tag for each platform]

Bloomberg is building the world's most trusted information network for financial professionals.

Learn more on our blog - [LINK to blog post as below]

[POSTER]

#sponsor #silver

### Blog

We are excited to announce our next Silver Sponsor for PyCon India 2024 - Bloomberg.

[Bloomberg Logo]

Bloomberg is dedicated to building the most trusted information network for financial professionals worldwide. With over 9,000 engineers, they are committed to innovating and developing new systems for the Bloomberg Terminal to tackle intricate real-world challenges. At Bloomberg, their teams have the autonomy to select the most suitable technologies for the task at hand, and Python often emerges as the preferred choice. They have fostered a vibrant community of more than 4,000 Python developers who have their hands in everything, from financial analytics and data science to contributing to open source technologies like Project Jupyter. Bloomberg is proud to be a Visionary Sponsor of the Python Software Foundation and host of many Python community events around the world. Learn more at https://techatbloomberg.com/python.

Follow Bloomberg on social media: X [1] and LinkedIn [2], and read more on its website [3].

[0] https://techatbloomberg.com/python
[1] https://x.com/TechAtBloomberg
[2] https://www.linkedin.com/company/bloomberg/
[3] https://www.techatbloomberg.com/

### Email Announcement for our Mailing List

Subject: Announcing the next Silver Sponsor for PyCon India 2024

Hi Everyone,
    
We are excited to announce our next Silver Sponsor for PyCon India 2024 - Bloomberg.

Bloomberg is building the world's most trusted information network for financial professionals. Its 9,000+ engineers are dedicated to advancing and building new systems for the Bloomberg Terminal to solve complex, real-world problems. They trust their teams to choose the right technologies for the job, and at Bloomberg, the answer is often Python. They employ an active community of 4,000+ Python developers who have their hands in everything from financial analytics and data science to contributing to open source technologies like Project Jupyter. Bloomberg is proud to be a Visionary Sponsor of the Python Software Foundation and host of many Python community events around the world. Learn more at [0].

Follow them on social media: X [1], LinkedIn [2], and read more on the company’s website [3].

We are immensely grateful to Bloomberg for its generous support.

Feel free to share the announcement blog post [4] in your network.

Stay tuned for more exciting updates!

[0] https://techatbloomberg.com/python
[1] https://x.com/TechAtBloomberg
[2] https://www.linkedin.com/company/bloomberg/
[3] https://www.techatbloomberg.com/
[4] [LINK to blog post as above]

Best Regards
<PyCon Team Member>
On Behalf of the PyCon India Team
