### ISSUE TITLE
[Comms] Announce PSF as Sponsor

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024-tasks#64]
Announce PSF as Gold Sponsor

> you can find[ our logo and official description for your event](https://wiki.python.org/psf/PSF%20Press%20Kit) website and/or conference printed material on our website. Our website URL is[ python.org/psf](http://www.python.org/psf), and our Twitter handle is[ @thepsf](https://twitter.com/ThePSF).

## Tasks
- [x] Writen Content, @Sc0rpi0n101 
- [ ] Poster/Graphic, @iamaravindsekar
- [ ] Website, @bhansa 

### Pre 4PM
- [ ] Mail Content
- [ ] Posters/Graphics
- [ ] Social Media Content
- [ ] Website PR

### Post 5PM
- [ ] Deploy Website
- [ ] Post on In-PyCon Mailing List
- [ ] Post on Social Media
- [ ] X-Post on other mailing lists

### Communication Channel (if needed for your task)

- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by WatchfulHitman** [comment]
Review Content:
- Writen Content, @Sc0rpi0n101
- Poster/Graphic, @iamaravindsekar
- Website, @bhansa @vamc-k
- review content, @sayanchowdhury @rayandas @palnabarun @Sc0rpi0n101 @harisibrahimkv


Riseup Pad; https://pad.riseup.net/p/B4WB5YY-QkNxArMPk57Y

Logo: 
![psf-logo-372x84](https://github.com/user-attachments/assets/eb057ce1-4813-43af-b82d-e8590b525ad8)

Poster: 
![Gold Sponsor-PSF](https://github.com/user-attachments/assets/c77c0861-4c6e-468f-a799-0db6004bdd1d)

**Comment by vamc-k** [comment]
Website PR: pythonindia/inpycon2024/pull/56
