### ISSUE TITLE
Announce Keynote Speaker -  Mars Lee

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2024-tasks#78]
Announcing Mars Lee as the final Keynote.

## Tasks
- [ ] Social Media Poster @iamaravindsekar
- [ ] Social Media announcement @WatchfulHitman 
- [ ] Blog post announcement @Sc0rpi0n101  
- [ ] Mailing list announcement  @WatchfulHitman 
- [ ] Website update to display the keynote speaker. @bhansa 

### Pre 4PM
- [ ] Push a low resolution image to server to refer in website and blog @bhansa 
- [ ] Merge the blog post @Sc0rpi0n101 
- [ ] Draft the social media announcement @WatchfulHitman  
- [ ] Merge the website changes @bhansa  

### Post 5PM
- [ ] Deploy the blog and the website @bhansa  
- [ ] Send the social media announcements out @WatchfulHitman  
- [ ] Announce on mailing list @WatchfulHitman 

### Communication Channel

- [ ] Mailing List
- [ ] Social Media

**Comment by sayanchowdhury** [comment]
Mars Lee is a Technical Illustrator that makes byte-sized comics that explain technical topics! She uses art, an under-represented skill set in open source, to get people excited about contributing. Her most recent works are the ‘[How to Contribute to NumPy](https://heyzine.com/flip-book/3e66a13901.html)’ comics and ‘[How to Write Alt Text for Scientific Diagrams and Documentation](https://heyzine.com/flip-book/f3c7f85cdc.html)’ comic.

Outside of conferences, you can find her making zines and rollerskating across NYC. You can connect with her on [Twitter/X](https://x.com/marsbarlee) and [LinkedIn](https://www.linkedin.com/in/mars-lee/).

**Comment by sayanchowdhury** [comment]
![marslee-headshot-smaller-size-square](https://github.com/user-attachments/assets/83bc03a6-fbb7-49a2-b9c8-16f9b9301ae5)

**Comment by iamaravindsekar** [comment]
Shall I have the Bio as Technical Instructor at PyData?

**Comment by iamaravindsekar** [comment]
Keynote speaker poster can be found in the following Google Drive url,

https://drive.google.com/file/d/120fxTj44pATEJ4tlMxEIobDWhN9q9We_/view?usp=sharing

**Comment by harisibrahimkv** [comment]
# Mailing list
------------
Finally, the cherry on top of the cake, our final keynote speaker - Mars Lee!

If you've ever been into comic books in your life, then this is only going to double your excitement. And if you haven't been into them, well this is probably your calling.

Mars Lee is a Technical Illustrator who makes byte-sized comics that explain technical topics! She uses art, an under-represented skill set in open source, to get people excited about contributing. Her most recent works are the "How to Contribute to NumPy" [0] and "How to Write Alt Text for Scientific Diagrams and Documentation" [1] comics.

Outside of conferences, you can find her making zines and rollerskating across NYC. Get to know more about her on both Twitter/X [2] and LinkedIn [3].

A uniquely talented individual, we are happy to have her at this year's conference to share her experiences with you and for you folks to learn from.

[0] https://heyzine.com/flip-book/3e66a13901.html
[1] https://heyzine.com/flip-book/f3c7f85cdc.html
[2] https://x.com/marsbarlee
[3] https://www.linkedin.com/in/mars-lee/

Twitter
-------
Finally, the final keynote speaker announcement that all of you (and us) were waiting for - Mars Lee! She is a Technical Illustrator and a passionate programmer.  Get to know more about her at our blog: <blog_lin>

See you folks at the conf!

Other SM
----------
Wrapping up our keynote announcements, we have our final keynote announcement to make - Mars Lee!

She'll be at PyCon India 2024 showcasing her illustrative genius in the world of technology where she makes it more creative and even more fun. For those among you having had comic books close to your hearts, you really don't want to miss this opportunity. And if this is your first time reading comics, her skill will make sure you fall in love with it.

Get to know more about her at our blog: <blog_link>

See y'all at PyCon India!
