### ISSUE TITLE
[Comms] Social media announcement for the scholarship

### ISSUE THREAD

**Issue by bhavin192** [pythonindia/inpycon2024-tasks#79]
We announced the need-basis scholarship early this week with emails going out. Need to post about it on SM as well. 

Page: https://in.pycon.org/2024/scholarship/

## Tasks
- [ ] Initial announcement @WatchfulHitman 
- [ ] Based on response we get we decide whether to do a reminder or not. 

### Communication Channel (if needed for your task)

- [x] Mailing List
  - [x] InPyCon
  - [x] X-Posts
    - [x] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook
