### ISSUE TITLE
[Comms] Announcing next Gold Sponsor LYZR AI

### ISSUE THREAD

**Issue by WatchfulHitman** [pythonindia/inpycon2024-tasks#81]
Review of Content:

Riseup Pad : https://pad.riseup.net/p/Mb9xAqFes95kSYcGuBA8

poster: 
![Gold Sponsor-Lyzer](https://github.com/user-attachments/assets/3270ce2c-3303-4aa6-8459-779f29200bbc)

## Tasks
- [ ] Review of content, @sayanchowdhury @rayandas @palnabarun @Sc0rpi0n101 @harisibrahimkv @kalyan678
- [ ]  Blog Creation, @Sc0rpi0n101, @harisibrahimkv 
- [ ]  Posting of blog on website, @bhansa @vamc-k
- [ ]  Poster Creation, @iamaravindsekar

### Pre 4PM
- [ ] Review of content, @sayanchowdhury @rayandas @palnabarun @Sc0rpi0n101 @harisibrahimkv
- [ ]  Blog Creation, @Sc0rpi0n101, @harisibrahimkv 
- [ ]  Posting of blog on website, @bhansa @vamc-k
- [ ]  Poster Creation, @iamaravindsekar

### Post 5PM
- [ ] posting content and mailing, @WatchfulHitman @tankala

### Communication Channel (if needed for your task)

- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by kalyan678** [comment]
@WatchfulHitman - I slightly rephrased the line . Rest all LGTM!

**Comment by anistark** [comment]
Lyzr logo: https://drive.google.com/file/d/1dUqGCjVeval65ShkOF2HstKNFRCqApWC/view?usp=sharing

**Comment by anistark** [comment]
This is done.
