### ISSUE TITLE
[Comms] Announce Next Gold Sponsor NPCI

### ISSUE THREAD

**Issue by RiteshAgrawal** [pythonindia/inpycon2024-tasks#82]
Describe your task need and goal here

Announcement Date: <EXACT DATE and TIME>, 2024

## Tasks
- [ ] Review of content, @sayanchowdhury @rayandas @palnabarun @Sc0rpi0n101 @harisibrahimkv @kalyan678
 - [ ] Blog Creation, @Sc0rpi0n101, @harisibrahimkv
 - [ ] Posting of blog on website, @bhansa @vamc-k
 - [ ] Poster Creation, @iamaravindsekar

### Pre 4PM
- [ ] Review of content, @sayanchowdhury @rayandas @palnabarun @Sc0rpi0n101 @harisibrahimkv
 - [ ] Blog Creation, @Sc0rpi0n101, @harisibrahimkv
 - [ ] Posting of blog on website, @bhansa @vamc-k
- [ ] Poster Creation, @iamaravindsekar

### Post 5PM
- [ ] posting content and mailing, @WatchfulHitman @tankala

### Communication Channel (if needed for your task)

- [ ] Mailing List
  - [ ] InPyCon
  - [ ] X-Posts
    - [ ] All Local Python User Groups
- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by anistark** [comment]
This is done.
