### ISSUE TITLE
Tracking Sayan's deliverables.

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2024-tasks#83]
- [ ] Insurance
- [ ] CoC 
	- [ ] Add the Reporting Guide
	- [ ] Add a few elements to CoC Main document
	- [ ] Draft an internal SOP document for during the event
	- [ ] Conduct the last 3 trainings
- [ ] Food
	- [ ] Ask Shakun to add the price for more items in snacks
	- [ ] Report to Shakun on how many tables and chair we need
	- [ ] Ask to increase food count
- [ ] Childcare 
	- [ ] Update the website
	- [ ] Social Media Announcement
- [ ] Transportation
	- [ ] Talk to the Transportation person
- [ ] Internet
	- [ ] Best quality internet at the venue
- [ ] Workshop Tickets
	- [ ] Gate the Workshop Tickets
