### ISSUE TITLE
Blog Post and SM announcement: Panels at PyCon India 2024

### ISSUE THREAD

**Issue by wavicles** [pythonindia/inpycon2024-tasks#87]
Scheduled for **18th September, 2024 **

## Tasks
- [x] Prepare a blog post  @wavicles  @vellankikoti @Sc0rpi0n101 
- [x] Prepare the content for the social media post, and get a poster from the design team @vellankikoti    @Sc0rpi0n101
- [ ] Social media announcement @WatchfulHitman

### Pre 4 PM
- [x] Review the content of blog post @anistark @palnabarun 
- [x] Merge the blog post
- [ ] Draft the social media announcement  @WatchfulHitman

### Post 5 PM
- [x] Deploy the blog on the website @palnabarun 
- [ ] Send the social media announcements out  @WatchfulHitman

### Communication Channels

- [ ] Social Media
  - [ ]  Twitter
  - [ ]  Linkedin
  - [ ]  Mastodon
  - [ ]  Instagram
  - [ ]  Facebook

**Comment by wavicles** [comment]
@Sc0rpi0n101 [doc for blog post content](https://docs.google.com/document/d/1kT_hio86AZJt0dDn6LVLiOd-MoysJIOnkcXlKrmbQOU/edit?usp=sharing)

**Comment by wavicles** [comment]
@anistark Please see when this can be scheduled.

**Comment by wavicles** [comment]
@WatchfulHitman sample content for social media posts is added at the end of the [bogpost doc ](https://docs.google.com/document/d/1kT_hio86AZJt0dDn6LVLiOd-MoysJIOnkcXlKrmbQOU/edit?usp=sharingl)

**Comment by anistark** [comment]
This was done.
